plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlinx.serialization)
}

// Sample tests in /content/reading/*.json are embedded into code at build time, so the apps work
// offline on first launch and the backend serves the same source of truth.
// Values are declared INSIDE register {} so doLast only captures locals (configuration-cache safe).
val generateBundledContent =
    tasks.register("generateBundledContent") {
        val contentDir = rootProject.layout.projectDirectory.dir("content/reading")
        val generatedDir = layout.buildDirectory.dir("generated/bundledContent/commonMain/kotlin")
        inputs.dir(contentDir)
        outputs.dir(generatedDir)
        doLast {
            val files =
                contentDir.asFile
                    .listFiles { file -> file.extension == "json" }
                    .orEmpty()
                    .sortedBy { it.name }
            val entries =
                files.joinToString(separator = ",\n") { file ->
                    val escaped =
                        file
                            .readText()
                            .replace("\\", "\\\\")
                            .replace("\"", "\\\"")
                            .replace("$", "\\$")
                            .replace("\r", "")
                            .replace("\n", "\\n")
                    "        \"$escaped\""
                }
            val output =
                generatedDir
                    .get()
                    .file("com/app/platform/language/core/model/content/BundledContent.kt")
                    .asFile
            output.parentFile.mkdirs()
            output.writeText(
                buildString {
                    appendLine(
                        "// Generated by :core:model:generateBundledContent from content/reading/*.json — do not edit.",
                    )
                    appendLine("package com.app.platform.language.core.model.content")
                    appendLine()
                    appendLine("public object BundledContent {")
                    appendLine("    public val readingTestsJson: List<String> = listOf(")
                    appendLine(entries)
                    appendLine("    )")
                    appendLine("}")
                },
            )
        }
    }

kotlin {
    jvmToolchain(17)

    android {
        namespace = "com.app.platform.language.core.model"
        compileSdk =
            libs.versions.compileSdk
                .get()
                .toInt()
        minSdk =
            libs.versions.minSdk
                .get()
                .toInt()
        withHostTest {}
    }
    jvm()
    iosArm64()
    iosSimulatorArm64()
    macosArm64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBundledContent)
            dependencies {
                api(libs.kotlinx.serialization.json)
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}
