plugins {
  alias(libs.plugins.kotlinMultiplatform)
  alias(libs.plugins.android.kotlin.multiplatform.library)
  alias(libs.plugins.kotlinx.serialization)
}

// Embeds content/*/*.json for offline first launch; locals keep doLast configuration-cache safe.
val generateBundledContent =
  tasks.register("generateBundledContent") {
    val contentDirs =
      mapOf(
        "readingTestsJson" to rootProject.layout.projectDirectory.dir("content/reading"),
        "listeningTestsJson" to rootProject.layout.projectDirectory.dir("content/listening"),
        "writingPromptsJson" to rootProject.layout.projectDirectory.dir("content/writing"),
      )
    val generatedDir = layout.buildDirectory.dir("generated/bundledContent/commonMain/kotlin")
    contentDirs.values.forEach { inputs.dir(it) }
    outputs.dir(generatedDir)
    doLast {
      val properties =
        contentDirs.map { (property, contentDir) ->
          val entries =
            contentDir.asFile
              .listFiles { file -> file.extension == "json" }
              .orEmpty()
              .sortedBy { it.name }
              .joinToString(separator = ",\n") { file ->
                val escaped =
                  file
                    .readText()
                    .replace("\\", "\\\\")
                    .replace("\"", "\\\"")
                    .replace("$", "\\$")
                    .replace("\r", "")
                    .replace("\n", "\\n")
                "        \"$escaped\""
              }
          "    public val $property: List<String> = listOf(\n$entries\n    )"
        }
      val output =
        generatedDir
          .get()
          .file("com/app/platform/language/core/model/content/BundledContent.kt")
          .asFile
      output.parentFile.mkdirs()
      output.writeText(
        buildString {
          appendLine(
            "// Generated by :core:model:generateBundledContent from content/{reading,listening,writing}/*.json — do not edit.",
          )
          appendLine("package com.app.platform.language.core.model.content")
          appendLine()
          appendLine("public object BundledContent {")
          properties.forEach { appendLine(it) }
          appendLine("}")
        },
      )
    }
  }

kotlin {
  jvmToolchain(17)

  android {
    namespace = "com.app.platform.language.core.model"
    compileSdk =
      libs.versions.compileSdk
        .get()
        .toInt()
    minSdk =
      libs.versions.minSdk
        .get()
        .toInt()
    withHostTest {}
  }
  jvm()
  iosArm64()
  iosSimulatorArm64()
  macosArm64()

  sourceSets {
    commonMain {
      kotlin.srcDir(generateBundledContent)
      dependencies {
        api(libs.kotlinx.serialization.json)
        api(libs.kotlin.result)
        api(libs.kotlin.result.coroutines)
      }
    }
    commonTest.dependencies {
      implementation(kotlin("test"))
    }
  }
}
